/**
 * Synthetic-export marking — one source of truth for how the Mock engine's
 * output gets flagged when it leaves the app.
 *
 * The Mock engine fabricates plausible-looking numbers for interface testing.
 * Nothing it produces may ever leave the app looking like a genuine SWMM run,
 * so every export/copy path routes its filename and/or content through these
 * pure helpers. Keeping the logic here (rather than inline in each React
 * handler) makes the guarantee testable and prevents the paths from drifting
 * apart.
 *
 * Convention (matching what the UI already used):
 *   - filename marker:  a `_SYNTHETIC` suffix inserted before the extension
 *   - in-content banner: SYNTHETIC_TEXT_HEADER prepended to text artifacts
 *   - canvas artifacts:  drawSyntheticWatermark (see SyntheticWarning.tsx)
 */

/**
 * The one-line stamp used in banners and canvas watermarks. Kept here (in a
 * React-free module) so both the UI components and the pure export helpers —
 * and the tests that cover them — share a single string.
 */
export const SYNTHETIC_MARK = 'SYNTHETIC RESULTS — NOT SWMM OUTPUT';

/** Multi-line banner prepended to synthetic text artifacts. */
export const SYNTHETIC_TEXT_HEADER =
  '*** ' + SYNTHETIC_MARK + ' ***\n' +
  '*** Generated by the Mock engine for interface testing only. ***\n' +
  '*** Do not use these values for engineering decisions. ***\n\n';

/** The filename token stamped into synthetic artifacts. */
export const SYNTHETIC_FILENAME_MARKER = '_SYNTHETIC';

/**
 * Does this result set come from the Mock engine? This is the single predicate
 * every export path must use to decide whether to apply synthetic marking.
 * Anything that is not explicitly the Mock engine is treated as real output.
 */
export function isSyntheticResults(
  results: { engineUsed?: string } | null | undefined,
): boolean {
  return results?.engineUsed === 'mock';
}

/**
 * Build a download filename, inserting the `_SYNTHETIC` marker before the
 * extension when the artifact is synthetic. Any extra suffix (e.g. an engine
 * tag) is placed before the synthetic marker so the marker sits immediately
 * before the extension.
 *
 *   syntheticFilename('model', '.rpt', true)          -> 'model_SYNTHETIC.rpt'
 *   syntheticFilename('model', '.rpt', false)         -> 'model.rpt'
 *   syntheticFilename('model', '.rpt', true, '_swmm5') -> 'model_swmm5_SYNTHETIC.rpt'
 */
export function syntheticFilename(
  base: string,
  ext: string,
  synthetic: boolean,
  extraSuffix = '',
): string {
  const dot = ext && !ext.startsWith('.') ? `.${ext}` : ext;
  return `${base}${extraSuffix}${synthetic ? SYNTHETIC_FILENAME_MARKER : ''}${dot}`;
}

/**
 * Prepend the synthetic banner to a text artifact when it is synthetic.
 * Real output is returned unchanged.
 */
export function markSyntheticText(body: string, synthetic: boolean): string {
  return synthetic ? SYNTHETIC_TEXT_HEADER + body : body;
}
