/**
 * Calibration parsing and export round-trip tests.
 * Run with: npx tsx tests/calibration.test.ts
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---- Inline minimal copies of the calibration functions under test ----
// (We duplicate the core logic here to avoid importing React-heavy swmm-ui.tsx.)

interface CalibrationPoint {
  nodeId: string;
  dateTime: string;
  value: number;
}
interface CalibrationDataSet {
  variable: string;
  category: 'node' | 'link' | 'subcatch';
  points: CalibrationPoint[];
  name?: string;
}

const CALIB_FILENAME_VARS: Record<string, { variable: string; category: 'node' | 'link' | 'subcatch' }> = {
  flow: { variable: 'Flow', category: 'link' },
  depth: { variable: 'Depth', category: 'node' },
  velocity: { variable: 'Velocity', category: 'link' },
  runoff: { variable: 'Runoff', category: 'subcatch' },
  flooding: { variable: 'Flooding', category: 'node' },
  head: { variable: 'Head', category: 'node' },
};

function parseCalibrationFile(text: string, fileName?: string): CalibrationDataSet {
  let variable = 'Unknown';
  let category: 'node' | 'link' | 'subcatch' = 'node';

  if (fileName) {
    const base = fileName.toLowerCase().replace(/\.(dat|txt|cal)$/i, '');
    for (const [key, meta] of Object.entries(CALIB_FILENAME_VARS)) {
      if (base.includes(key)) { variable = meta.variable; category = meta.category; break; }
    }
  }

  const lines = text.split(/\r?\n/);
  let currentId = '';
  const points: CalibrationPoint[] = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    // Parse header directives first (they start with ;; so must be checked before skipping comments)
    const headerVar = line.match(/^;;\s*Variable:\s*(.+)/i);
    if (headerVar) { variable = headerVar[1].trim(); continue; }
    const headerCat = line.match(/^;;\s*Category:\s*(.+)/i);
    if (headerCat) {
      const c = headerCat[1].trim().toLowerCase();
      if (c === 'link') category = 'link';
      else if (c === 'subcatch' || c === 'subcatchment') category = 'subcatch';
      else category = 'node';
      continue;
    }

    if (line.startsWith(';')) continue;

    const parts = line.split(/\s+/);
    const firstIsNumeric = /^[\d.\/:]+$/.test(parts[0]);

    if (parts.length === 1) { currentId = parts[0]; continue; }

    if (!firstIsNumeric) {
      currentId = parts[0];
      if (parts.length >= 4) {
        const value = parseFloat(parts[parts.length - 1]);
        if (!isNaN(value)) points.push({ nodeId: parts[0], dateTime: parts.slice(1, parts.length - 1).join(' '), value });
      } else if (parts.length === 3) {
        const value = parseFloat(parts[2]);
        if (!isNaN(value)) points.push({ nodeId: parts[0], dateTime: parts[1], value });
      }
    } else if (currentId && parts.length >= 2) {
      const value = parseFloat(parts[parts.length - 1]);
      if (!isNaN(value)) points.push({ nodeId: currentId, dateTime: parts.slice(0, parts.length - 1).join(' '), value });
    }
  }

  return { variable, category, points, name: fileName };
}

function generateCalibrationFile(ds: CalibrationDataSet): string {
  const lines: string[] = [];
  lines.push(`;; SWMM Calibration Data File`);
  lines.push(`;; Generated by SWMM5-UI`);
  lines.push(`;; Variable: ${ds.variable}`);
  lines.push(`;; Category: ${ds.category}`);
  lines.push(``);

  const byLocation = new Map<string, CalibrationPoint[]>();
  for (const pt of ds.points) {
    if (!byLocation.has(pt.nodeId)) byLocation.set(pt.nodeId, []);
    byLocation.get(pt.nodeId)!.push(pt);
  }

  for (const [locId, pts] of byLocation) {
    lines.push(locId);
    for (const pt of pts) {
      lines.push(`           ${pt.dateTime.padEnd(20)} ${pt.value}`);
    }
    lines.push(``);
  }

  return lines.join('\n');
}

// ---- Test helpers ----
let passed = 0;
let failed = 0;

function expect(label: string, actual: unknown, expected: unknown): void {
  const ok = JSON.stringify(actual) === JSON.stringify(expected);
  if (ok) {
    console.log(`  ✓ ${label}`);
    passed++;
  } else {
    console.error(`  ✗ ${label}`);
    console.error(`    expected: ${JSON.stringify(expected)}`);
    console.error(`    actual:   ${JSON.stringify(actual)}`);
    failed++;
  }
}

function expectTrue(label: string, value: boolean): void {
  expect(label, value, true);
}

// ---- Tests ----

console.log('\n=== Calibration Parser Tests ===\n');

// 1. Official SWMM block format (station on own line, indented rows)
{
  console.log('1. Official SWMM block format');
  const text = `
;Flows for Selected Conduits
;Conduit  Days  Time  Flow

1030
           0     0:15  0
           0     0:30  23.88
           0     1:00  94.58
1602
           0     0:15  5.76
           0     0:30  38.51
`;
  const ds = parseCalibrationFile(text, 'flow_conduits.dat');
  expect('variable inferred from filename', ds.variable, 'Flow');
  expect('category inferred from filename', ds.category, 'link');
  expect('point count', ds.points.length, 5);
  expect('first point nodeId', ds.points[0].nodeId, '1030');
  expect('first point value', ds.points[0].value, 0);
  expect('second point value', ds.points[1].value, 23.88);
  expect('fourth point nodeId', ds.points[3].nodeId, '1602');
  expect('fourth point value', ds.points[3].value, 5.76);
}

// 2. Calendar-date format (4-token rows)
{
  console.log('\n2. Calendar-date 4-token rows (ID Date Time Value)');
  const text = `
;; Variable: Depth
;; Category: node

N1 01/15/2024 10:00 1.5
N1 01/15/2024 11:00 2.3
N2 01/15/2024 10:00 0.8
`;
  const ds = parseCalibrationFile(text);
  expect('variable from header', ds.variable, 'Depth');
  expect('category from header', ds.category, 'node');
  expect('point count', ds.points.length, 3);
  expect('N2 point value', ds.points[2].value, 0.8);
}

// 3. Numeric station ID (e.g. gauge number)
{
  console.log('\n3. Numeric station ID');
  const text = `
82309600
  01/01/2007 10:00 1.5
  01/01/2007 10:15 1.6
`;
  const ds = parseCalibrationFile(text);
  expect('point count', ds.points.length, 2);
  expect('station ID', ds.points[0].nodeId, '82309600');
  expect('value', ds.points[1].value, 1.6);
}

// 4. Comment lines are skipped
{
  console.log('\n4. Comment lines are skipped');
  const text = `
;; Variable: Flow
;; Category: link
; This line is a comment
;; Another comment

C1
  0  0:30  5.5
`;
  const ds = parseCalibrationFile(text);
  expect('point count (comment lines skipped)', ds.points.length, 1);
  expect('point nodeId', ds.points[0].nodeId, 'C1');
}

// 5. Export → re-import round-trip
{
  console.log('\n5. Round-trip: export then re-import');
  const original: CalibrationDataSet = {
    variable: 'Flow',
    category: 'link',
    name: 'test.dat',
    points: [
      { nodeId: '1030', dateTime: '01/15/2024 10:00', value: 23.88 },
      { nodeId: '1030', dateTime: '01/15/2024 11:00', value: 94.58 },
      { nodeId: '1602', dateTime: '01/15/2024 10:00', value: 5.76 },
    ],
  };
  const exported = generateCalibrationFile(original);
  const reimported = parseCalibrationFile(exported);

  expect('variable preserved', reimported.variable, original.variable);
  expect('category preserved', reimported.category, original.category);
  expect('point count preserved', reimported.points.length, original.points.length);
  expect('first nodeId preserved', reimported.points[0].nodeId, '1030');
  expect('first value preserved', reimported.points[0].value, 23.88);
  expect('third nodeId preserved', reimported.points[2].nodeId, '1602');
}

// 6. Export uses correct SWMM block format (station ID on own line)
{
  console.log('\n6. Export format: station ID on its own line');
  const ds: CalibrationDataSet = {
    variable: 'Depth', category: 'node', name: 'depth.dat',
    points: [{ nodeId: 'JCT-1', dateTime: '01/01/2024 12:00', value: 2.5 }],
  };
  const out = generateCalibrationFile(ds);
  const lines = out.split('\n').filter(l => l.trim() && !l.startsWith(';'));
  expect('first data line is station ID only', lines[0], 'JCT-1');
  expectTrue('measurement row is indented', lines[1].startsWith('           '));
  expectTrue('measurement row contains value', lines[1].includes('2.5'));
}

// 7. Filename variable inference
{
  console.log('\n7. Filename variable inference');
  expect('flow', parseCalibrationFile('', 'flow_obs.dat').variable, 'Flow');
  expect('depth', parseCalibrationFile('', 'depth_gauge.dat').variable, 'Depth');
  expect('velocity', parseCalibrationFile('', 'velocity.txt').variable, 'Velocity');
  expect('runoff', parseCalibrationFile('', 'subcatch_runoff.dat').variable, 'Runoff');
  expect('unknown filename', parseCalibrationFile('', 'mystery.dat').variable, 'Unknown');
}

// ---- Summary ----
console.log(`\n${'─'.repeat(40)}`);
console.log(`Calibration tests: ${passed} passed, ${failed} failed\n`);
if (failed > 0) process.exit(1);
