import { AlertTriangle } from 'lucide-react';

const STRIPES = 'repeating-linear-gradient(45deg, #b45309 0, #b45309 10px, #92400e 10px, #92400e 20px)';

export const SYNTHETIC_MARK = 'SYNTHETIC RESULTS — NOT SWMM OUTPUT';

export const SYNTHETIC_TEXT_HEADER =
  '*** ' + SYNTHETIC_MARK + ' ***\n' +
  '*** Generated by the Mock engine for interface testing only. ***\n' +
  '*** Do not use these values for engineering decisions. ***\n\n';

export function drawSyntheticWatermark(ctx: CanvasRenderingContext2D, width: number, height: number) {
  ctx.save();
  ctx.fillStyle = '#b45309';
  ctx.fillRect(0, 0, width, 24);
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 13px "JetBrains Mono", monospace';
  ctx.textBaseline = 'middle';
  ctx.fillText(SYNTHETIC_MARK, 10, 12);
  ctx.translate(width / 2, height / 2);
  ctx.rotate(-Math.PI / 6);
  ctx.globalAlpha = 0.18;
  ctx.fillStyle = '#b45309';
  ctx.font = `bold ${Math.max(24, Math.floor(width / 22))}px "JetBrains Mono", monospace`;
  ctx.textAlign = 'center';
  ctx.fillText(SYNTHETIC_MARK, 0, 0);
  ctx.restore();
}

export function SyntheticResultsBanner() {
  return (
    <div
      className="flex items-center gap-2 px-3 py-1.5 text-white shrink-0"
      style={{ background: STRIPES }}
      data-testid="banner-synthetic-results"
    >
      <AlertTriangle className="w-4 h-4 shrink-0" />
      <span className="text-[11px] font-bold tracking-wide">
        SYNTHETIC RESULTS — NOT SWMM OUTPUT. The Mock engine generated these values for testing only; do not use them for engineering decisions.
      </span>
    </div>
  );
}

export const REPORT_SUMMARY_MESSAGE =
  'Summary values from SWMM report; binary time-series results were unavailable.';

export function ReportSummaryBanner() {
  return (
    <div
      className="flex items-center gap-2 px-3 py-1.5 shrink-0"
      style={{ background: '#fdf6e8', borderBottom: '1px solid #e0c88a', color: '#7a5c14' }}
      data-testid="banner-report-summary"
    >
      <AlertTriangle className="w-4 h-4 shrink-0" />
      <span className="text-[11px] font-semibold tracking-wide">
        REPORT SUMMARY ONLY — {REPORT_SUMMARY_MESSAGE} Summary tables and continuity errors are genuine; time-series animation, graphs, and time-dependent maps are unavailable for this run.
      </span>
    </div>
  );
}

export function ReportSummaryLabel({ compact = false }: { compact?: boolean }) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-sm font-bold tracking-wide ${compact ? 'px-1.5 py-0 text-[8px]' : 'px-2 py-0.5 text-[10px]'}`}
      style={{ background: '#fdf6e8', border: '1px solid #e0c88a', color: '#7a5c14' }}
      title={REPORT_SUMMARY_MESSAGE}
      data-testid="label-report-summary"
    >
      <AlertTriangle className={compact ? 'w-2.5 h-2.5' : 'w-3 h-3'} />
      REPORT SUMMARY ONLY — NO TIME SERIES
    </span>
  );
}

/** Full-size empty state shown inside analysis dialogs when only report-summary results exist. */
export function ReportSummaryNotice({ feature = 'This view' }: { feature?: string }) {
  return (
    <div
      className="flex flex-col items-center gap-2 rounded border px-6 py-10 text-center"
      style={{ background: '#fdf6e8', borderColor: '#e0c88a', color: '#7a5c14' }}
      data-testid="notice-report-summary"
    >
      <AlertTriangle className="w-6 h-6" />
      <div className="text-sm font-semibold">{feature} is unavailable for this run</div>
      <div className="text-xs max-w-md">
        {REPORT_SUMMARY_MESSAGE} Only the report's summary tables and continuity errors are genuine engine
        output — open the SWMM Report (Project &gt; Report) to view them.
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * Decimated (sampled) results — the run produced more reporting periods
 * than the browser loads, so the series spans the whole run but skips
 * intermediate periods.
 * ------------------------------------------------------------------ */

export interface TruncationInfo {
  actual: number;
  loaded: number;
  stride: number;
}

/** Pull the truncation facts off a results object, or null when nothing was dropped. */
export function getTruncationInfo(results: {
  isTruncated?: boolean;
  actualReportingSteps?: number;
  loadedReportingSteps?: number;
  samplingStride?: number;
} | null | undefined): TruncationInfo | null {
  if (!results?.isTruncated) return null;
  const actual = results.actualReportingSteps ?? 0;
  const loaded = results.loadedReportingSteps ?? 0;
  if (actual <= loaded) return null;
  return { actual, loaded, stride: results.samplingStride ?? 1 };
}

export function truncationMessage({ actual, loaded, stride }: TruncationInfo): string {
  return `This run wrote ${actual.toLocaleString()} reporting periods — more than the browser loads at once. ` +
    `Every ${stride === 2 ? '2nd' : stride === 3 ? '3rd' : `${stride}th`} period was sampled, giving ${loaded.toLocaleString()} steps ` +
    `that span the full simulation. Peaks between sampled periods are not shown; read exact peak values from the SWMM report.`;
}

export function TruncatedResultsBanner({ info }: { info: TruncationInfo }) {
  return (
    <div
      className="flex items-center gap-2 px-3 py-1.5 shrink-0"
      style={{ background: '#eef4fd', borderBottom: '1px solid #9dbde8', color: '#1c4b8a' }}
      data-testid="banner-truncated-results"
    >
      <AlertTriangle className="w-4 h-4 shrink-0" />
      <span className="text-[11px] font-semibold tracking-wide">
        SAMPLED TIME SERIES — {truncationMessage(info)}
      </span>
    </div>
  );
}

export function TruncatedResultsLabel({ info, compact = false, scope, testId }: {
  info: TruncationInfo;
  compact?: boolean;
  /** Which run this describes, when more than one is on screen (e.g. "compare"). */
  scope?: string;
  testId?: string;
}) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-sm font-bold tracking-wide ${compact ? 'px-1.5 py-0 text-[8px]' : 'px-2 py-0.5 text-[10px]'}`}
      style={{ background: '#eef4fd', border: '1px solid #9dbde8', color: '#1c4b8a' }}
      title={`${scope ? `${scope}: ` : ''}${truncationMessage(info)}`}
      data-testid={testId || 'label-truncated-results'}
    >
      <AlertTriangle className={compact ? 'w-2.5 h-2.5' : 'w-3 h-3'} />
      {scope ? `${scope.toUpperCase()} ` : ''}SAMPLED 1-IN-{info.stride}
    </span>
  );
}

/**
 * In-surface notice for analysis views (statistics, model health) whose numbers
 * are integrated over the loaded series.
 */
export function TruncatedResultsNotice({ info, what }: { info: TruncationInfo; what: string }) {
  return (
    <div
      className="rounded-sm px-3 py-2 text-[11px] leading-snug"
      style={{ background: '#eef4fd', border: '1px solid #9dbde8', color: '#1c4b8a' }}
      data-testid="notice-truncated-results"
    >
      <span className="font-bold">Sampled results — </span>
      {what} is computed from {info.loaded.toLocaleString()} of this run&apos;s {info.actual.toLocaleString()} reporting
      periods (every {info.stride === 2 ? '2nd' : info.stride === 3 ? '3rd' : `${info.stride}th`} period).
      Durations and volumes use the real gaps between samples, but short spikes falling between them are not counted.
      Check the SWMM report for exact peaks and totals.
    </div>
  );
}

export function SyntheticResultsLabel({ compact = false }: { compact?: boolean }) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-sm font-bold tracking-wide text-white ${compact ? 'px-1.5 py-0 text-[8px]' : 'px-2 py-0.5 text-[10px]'}`}
      style={{ background: STRIPES }}
      data-testid="label-synthetic-results"
    >
      <AlertTriangle className={compact ? 'w-2.5 h-2.5' : 'w-3 h-3'} />
      SYNTHETIC RESULTS — NOT SWMM OUTPUT
    </span>
  );
}
