import { AlertTriangle } from 'lucide-react';

const STRIPES = 'repeating-linear-gradient(45deg, #b45309 0, #b45309 10px, #92400e 10px, #92400e 20px)';

export const SYNTHETIC_MARK = 'SYNTHETIC RESULTS — NOT SWMM OUTPUT';

export const SYNTHETIC_TEXT_HEADER =
  '*** ' + SYNTHETIC_MARK + ' ***\n' +
  '*** Generated by the Mock engine for interface testing only. ***\n' +
  '*** Do not use these values for engineering decisions. ***\n\n';

export function drawSyntheticWatermark(ctx: CanvasRenderingContext2D, width: number, height: number) {
  ctx.save();
  ctx.fillStyle = '#b45309';
  ctx.fillRect(0, 0, width, 24);
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 13px "JetBrains Mono", monospace';
  ctx.textBaseline = 'middle';
  ctx.fillText(SYNTHETIC_MARK, 10, 12);
  ctx.translate(width / 2, height / 2);
  ctx.rotate(-Math.PI / 6);
  ctx.globalAlpha = 0.18;
  ctx.fillStyle = '#b45309';
  ctx.font = `bold ${Math.max(24, Math.floor(width / 22))}px "JetBrains Mono", monospace`;
  ctx.textAlign = 'center';
  ctx.fillText(SYNTHETIC_MARK, 0, 0);
  ctx.restore();
}

export function SyntheticResultsBanner() {
  return (
    <div
      className="flex items-center gap-2 px-3 py-1.5 text-white shrink-0"
      style={{ background: STRIPES }}
      data-testid="banner-synthetic-results"
    >
      <AlertTriangle className="w-4 h-4 shrink-0" />
      <span className="text-[11px] font-bold tracking-wide">
        SYNTHETIC RESULTS — NOT SWMM OUTPUT. The Mock engine generated these values for testing only; do not use them for engineering decisions.
      </span>
    </div>
  );
}

export function SyntheticResultsLabel({ compact = false }: { compact?: boolean }) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-sm font-bold tracking-wide text-white ${compact ? 'px-1.5 py-0 text-[8px]' : 'px-2 py-0.5 text-[10px]'}`}
      style={{ background: STRIPES }}
      data-testid="label-synthetic-results"
    >
      <AlertTriangle className={compact ? 'w-2.5 h-2.5' : 'w-3 h-3'} />
      SYNTHETIC RESULTS — NOT SWMM OUTPUT
    </span>
  );
}
